apiVersion: v1
data:
  APP_FOLDER: /usr/src/app
  DATABASE: postgres
  DATABASE_URL: postgresql://hello_flask:hello_flask@db:5432/hello_flask_dev
  FLASK_APP: project/__init__.py
  FLASK_DEBUG: "1"
  SQL_HOST: db
  SQL_PORT: "5432"
kind: ConfigMap
metadata:
  name: env-dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: postgres-data
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: hello_flask_dev
            - name: POSTGRES_PASSWORD
              value: hello_flask
            - name: POSTGRES_USER
              value: hello_flask
          image: postgres:13-alpine
          name: db
          ports:
            - containerPort: 8002
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8002
  selector:
    app: db
status:
  loadBalancer: {}
