apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: web-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - args:
            - python
            - manage.py
            - run
            - -h
            - 0.0.0.0
            - -p
            - "8001"
          env:
            - name: APP_FOLDER
              valueFrom:
                configMapKeyRef:
                  key: APP_FOLDER
                  name: env-dev
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DATABASE
                  name: env-dev
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: env-dev
            - name: FLASK_APP
              valueFrom:
                configMapKeyRef:
                  key: FLASK_APP
                  name: env-dev
            - name: FLASK_DEBUG
              valueFrom:
                configMapKeyRef:
                  key: FLASK_DEBUG
                  name: env-dev
            - name: SQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: SQL_HOST
                  name: env-dev
            - name: SQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: SQL_PORT
                  name: env-dev
          image: web
          name: web
          ports:
            - containerPort: 8001
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app/
              name: web-claim0
      restartPolicy: Always
      volumes:
        - name: web-claim0
          persistentVolumeClaim:
            claimName: web-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    app: web
status:
  loadBalancer: {}
