pipeline {
    agent any
    tools {
        maven 'Maven_Home'
        allure 'Allure'
    }
    stages {
        stage('Build') {
            steps {
                sh "mvn clean -B -DskipTests clean package -f hello/pom.xml"
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -f hello/pom.xml'
            }
            post {
                always {
                    junit(
                    testResults: 'hello/target/surefire-reports/TEST-org.example.CalculatorTest.xml'
                    )
                }
            }
        }
        stage('Allure report') {
                steps {
                script {
                        allure([
                                includeProperties: false,
                                jdk: '',
                                properties: [],
                                reportBuildPolicy: 'ALWAYS',
                                results: [[path: 'target/surefire-reports/']]
                        ])
                }
                }
        }
    }
}
