version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    user: 0:0
    volumes:
    - ./jenkins_data:/var/jenkins_home
  sonarqube:
    image: sonarqube
    ports: 
      - "9000:9000"