pipeline {
    agent any
    tools {
        maven 'Maven_Home'
        allure 'Allure'
    }
    stages {
        stage('Build') {
            steps {
                sh "mvn clean install -f hello/pom.xml"
            }

            post {
                always {
                    junit(
                        testResults: 'hello/target/surefire-reports/TEST-*.xml'
                    )
                }
            }
        }
        stage('Allure report') {
                steps {
                script {
                  allure([
                          includeProperties: false,
                          jdk: '',
                          properties: [],
                          reportBuildPolicy: 'ALWAYS',
                          results: [[path: 'hello/target/surefire-reports/']]
                  ])
                }
                }
        }
        stage('Sonar') {
            steps {
                 sh 'mvn sonar:sonar -Dsonar.host.url=http://172.22.0.2:9000 -Dsonar.login=admin -Dsonar.password=111 -X -e -f hello/pom.xml'
           }
        }

        stage("Quality gate") {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }
    }
    post {
        always {
            cleanWs disableDeferredWipeout: true, deleteDirs: true
        }
    }
}
