- name: Deploy
  hosts: prom
  tasks:
    - name: Ensure java is installed
      apt:
        name: java
        state: present
        update_cache: true
    - name: Create dir
      file:
        path: ~/ci_cd
        state: directory
    - name: Unarchive distrib
      unarchive:
        src: hello/target/hello-1.0-SNAPSHOT.jar
        dest: ~/ci_cd
    - name: Run java
      shell: "nohup java -jar ~/ci_cd/hello-1.0-SNAPSHOT.jar &"
