FROM python:3.10.7-slim-buster

# WORKDIR /usr/src/app

EXPOSE 5000

# RUN apt-get update && apt-get install -y netcat

RUN pip install --upgrade pip
# COPY ./requirements.txt /usr/src/app/requirements.txt
# RUN pip install -r requirements.txt

# COPY . /usr/src/app/

# ENTRYPOINT ["python -m flask --app hello run"]