- name: ping
  ping:
    

- name: Create docker
  pip:
    name: "docker<5"
  become: yes

- name: Copy src
  copy:
    src: services/flask
    dest: ~/services/

- name: Run flask app
  docker_compose:
    definition:
      version: "2"
      services:
        web:
        build: 
          context: /root/services/flask/
          dockerfile: Dockerfile
          command: "python3 -m flask hello run"
          # volumes:
          #   - "services/flask:/code"
          ports:
            - "5000:8000"
