version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0 -p 8001
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - "8001:8001"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "8002:8002"
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
  nginx:
    build: ./services/nginx
    volumes:
      - ./services/:/usr/src/app/
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data: